// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7NPu_-zSAk_uCpiKBJ56yJHPG7W2gAI',
    appId: '1:550387847113:web:cf61187322825d75d12218',
    messagingSenderId: '550387847113',
    projectId: 'kivu-haqms',
    authDomain: 'kivu-haqms.firebaseapp.com',
    storageBucket: 'kivu-haqms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNwpJa0X1PckR6_pLb0io22oXOIcWbAA',
    appId: '1:550387847113:android:0c17dcca138a3a1dd12218',
    messagingSenderId: '550387847113',
    projectId: 'kivu-haqms',
    storageBucket: 'kivu-haqms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLIfb_yCQdBbXaj66ed-eaRmED9PVJ2Q',
    appId: '1:550387847113:ios:89cd4cdf1e312f31d12218',
    messagingSenderId: '550387847113',
    projectId: 'kivu-haqms',
    storageBucket: 'kivu-haqms.firebasestorage.app',
    iosBundleId: 'com.example.kivuHaqms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLIfb_yCQdBbXaj66ed-eaRmED9PVJ2Q',
    appId: '1:550387847113:ios:89cd4cdf1e312f31d12218',
    messagingSenderId: '550387847113',
    projectId: 'kivu-haqms',
    storageBucket: 'kivu-haqms.firebasestorage.app',
    iosBundleId: 'com.example.kivuHaqms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-7NPu_-zSAk_uCpiKBJ56yJHPG7W2gAI',
    appId: '1:550387847113:web:5bfd6d75ec6e6679d12218',
    messagingSenderId: '550387847113',
    projectId: 'kivu-haqms',
    authDomain: 'kivu-haqms.firebaseapp.com',
    storageBucket: 'kivu-haqms.firebasestorage.app',
  );
}
